### PR TITLE
add specific l_spank_get_item functions for different data types

### PR DESCRIPTION
**Pull request by ryanday36**
this fixes a bug where getting a uid_t type item (S_JOB_UID) as an uninitialized long led to bad values on some architectures by adding specific l_spank_get_item_ functions for different data types as specified in spank.h and initializing all values.

I've also added some newer data items (S_SLURM_RESTART_COUNT, S_SLURM_ARRAY_ID, S_SLURM_ARRAY_TASK_ID).

Tested on ruby. No errors for any of our lua plugins.

### CODE REVIEW

**Review by grondo — APPROVED** [review]
This looks good! Sorry for the bugs.

I'll go ahead and merge. Thanks!

**Comment by grondo** [comment]
Oh do you want to squash the two commits together first?

**Comment by ryanday36** [comment]
yeah, probably makes sense to squash and merge.

From: Mark Grondona ***@***.***>
Reply-To: chaos/slurm-spank-plugins ***@***.***>
Date: Thursday, May 27, 2021 at 2:50 PM
To: chaos/slurm-spank-plugins ***@***.***>
Cc: "Day, Ryan" ***@***.***>, Author ***@***.***>
Subject: Re: [chaos/slurm-spank-plugins] add specific l_spank_get_item functions for different data types (#10)


Oh do you want to squash the two commits together first?

**Comment by grondo** [comment]
We do like to keep merge commits in our projects (though not sure this one counts). I'm fine with squash and merge, but would prefer if you squashed the commits and did a force-push.

**Comment by ryanday36** [comment]
Alright. That appears to have Just Worked. Fun with git magic.

**Comment by grondo** [comment]
Thanks!

**Pull request merged**
