### PR TITLE
Various fixes for Lua 5.3, Slurm 19.05, and hwloc 2.x

### PR DESCRIPTION
**Pull request by grondo**
This is a batch of fixes and updates to get various plugins working with Slurm 19.05, hwloc 2.x and Lua 5.3.

The patches were developed on Ubuntu 20.04, but may be sufficient to work on RHEL 8/TOSS 4. However, I have not had a chance to test on that platform yet.

Please don't merge until this branch has been tested on a TOSS 4 system.

### CODE REVIEW

**Comment by grondo** [comment]
@ryanday36, I pushed a change to `lua/Makefile` that uses `pkg-config` instead of manual setting Lua paths. Hopefully this works on both RHEL8 and Ubuntu 20.04. If you have a chance, can you test and then we can merge this PR and tag a new version?

Thanks!

**Comment by ryanday36** [comment]
Hi Mark,

I didn’t try going through the buildfarm, but on opal63 (currently running toss4), the pkg-config version complains a bunch about not being able to find the appropriate .pc file:


[day36@opal63:lua]$ make

Package lua5.3 was not found in the pkg-config search path.

Perhaps you should add the directory containing `lua5.3.pc'

to the PKG_CONFIG_PATH environment variable

Package 'lua5.3', required by 'virtual:world', not found

Package lua5.3 was not found in the pkg-config search path.

Perhaps you should add the directory containing `lua5.3.pc'

to the PKG_CONFIG_PATH environment variable

Package 'lua5.3', required by 'virtual:world', not found

cc -I..   -g -Wall -DLIBLUA_DSO=\"\" -o lua.o -fPIC -c lua.c

Package lua5.3 was not found in the pkg-config search path.

Perhaps you should add the directory containing `lua5.3.pc'

to the PKG_CONFIG_PATH environment variable

Package 'lua5.3', required by 'virtual:world', not found

Package lua5.3 was not found in the pkg-config search path.

Perhaps you should add the directory containing `lua5.3.pc'

to the PKG_CONFIG_PATH environment variable

Package 'lua5.3', required by 'virtual:world', not found

cc -I..   -g -Wall -DLIBLUA_DSO=\"\" -o ../lib/list.o -fPIC -c ../lib/list.c

In file included from ../lib/list.c:38:

../lib/list.c: In function 'list_create':

../lib/list.c:231:12: warning: suggest parentheses around assignment used as truth value [-Wparentheses]

     assert(l->magic = LIST_MAGIC);      /* set magic via assert abuse */

            ^

../lib/list.c: In function 'list_destroy':

../lib/list.c:249:16: warning: suggest parentheses around assignment used as truth value [-Wparentheses]

         assert(i->magic = ~LIST_MAGIC); /* clear magic via assert abuse */

                ^

../lib/list.c:261:12: warning: suggest parentheses around assignment used as truth value [-Wparentheses]

     assert(l->magic = ~LIST_MAGIC);     /* clear magic via assert abuse */

            ^

../lib/list.c: In function 'list_iterator_create':

../lib/list.c:531:12: warning: suggest parentheses around assignment used as truth value [-Wparentheses]

     assert(i->magic = LIST_MAGIC);      /* set magic via assert abuse */

            ^

../lib/list.c: In function 'list_iterator_destroy':

../lib/list.c:568:12: warning: suggest parentheses around assignment used as truth value [-Wparentheses]

     assert(i->magic = ~LIST_MAGIC);     /* clear magic via assert abuse */

            ^

Package lua5.3 was not found in the pkg-config search path.

Perhaps you should add the directory containing `lua5.3.pc'

to the PKG_CONFIG_PATH environment variable

Package 'lua5.3', required by 'virtual:world', not found

cc -shared -o lua.so lua.o ../lib/list.o

[day36@opal63:lua]$

It does still build, but doesn’t have the expected library dependencies:


[day36@opal63:lua]$ ldd lua.so

       linux-vdso.so.1 (0x0000155555551000)

       libc.so.6 => /lib64/libc.so.6 (0x0000155554d5f000)

       /lib64/ld-linux-x86-64.so.2 (0x000015555532b000)

[day36@opal63:lua]$ ldd ../../ssp_t4/lua/lua.so

       linux-vdso.so.1 (0x0000155555551000)

       liblua-5.3.so => /lib64/liblua-5.3.so (0x0000155554ee6000)

       libc.so.6 => /lib64/libc.so.6 (0x0000155554b24000)

       libm.so.6 => /lib64/libm.so.6 (0x00001555547a2000)

       libdl.so.2 => /lib64/libdl.so.2 (0x000015555459e000)

       /lib64/ld-linux-x86-64.so.2 (0x000015555532b000)

[day36@opal63:lua]$

Ryan

**Comment by grondo** [comment]
Ah bummer! Sounds like EL8 doesn't include a pkg-config for lua5.3 or the name doesn't match. I'll retry again tomorrow. 

Thanks!

**Comment by grondo** [comment]
@ryanday36, if you have a chance, can you test this branch again on TOSS4?

I've tested the most recent changes on both CentOS 8 and Ubuntu 20.04.

**Comment by ryanday36** [comment]
Builds clean on a TOSS4 node.

**Comment by grondo** [comment]
> Builds clean on a TOSS4 node.

Thanks! Want to press the merge button on GitHub for me? ;-)  Then I'll work on a NEWS update and new tag.

**Comment by grondo** [comment]
Actually, I just went ahead and pushed an updated NEWS with this PR.

Once you approve @ryanday36, go ahead and merge this PR and I'll tag a new version, from which you can build RPMs in the build farm.

Thanks!

**Comment by grondo** [comment]
Thanks! I tagged 0.39, so try building new RPMs from that tag.

**Comment by ryanday36** [comment]
Successfully built for toss 4 from the 0.39 tag. Thank you for all the work Mark!

**Comment by grondo** [comment]
Thanks for the testing!

**Pull request merged**
