### PR TITLE
bump version number

### PR DESCRIPTION
**Pull request by ryanday36**
presumably this will grab my 0.38 tag as well...

### CODE REVIEW

**Comment by grondo** [comment]
You'll have to push your tag directly to the repo, e.g.

```console
$ git push origin 0.38
```

where `origin` is the name of your remote to the chaos/slurm-spank-plugins repo.
`git push https://github.com/chaos/slurm-spank-plugins 0.38` may also work.

**Comment by ryanday36** [comment]
Getting permission denied when I try to push to https://github.com/chaos/slurm-spank-plugins

[day36@rzhasgpu18:slurm-spank-plugins]$ git push origin 0.38
remote: Permission to chaos/slurm-spank-plugins.git denied to ryanday36.
fatal: unable to access 'https://github.com/chaos/slurm-spank-plugins.git/': The requested URL returned error: 403
[day36@rzhasgpu18:slurm-spank-plugins]$

**Comment by grondo** [comment]
Ah, yeah, I'll have @garlick add you to the chaos organization, then I think you'll be able to push the tag... I think...

**Comment by ryanday36** [comment]
Sweet. I have joined the chaos and pushed the tag. Thank you for walking me through everything. Now on to the buildfarm...

**Comment by grondo** [comment]
Have fun! :mountain_biking_man:

**Pull request merged**
