### PR TITLE
Add mpibind

### PR DESCRIPTION
**Pull request by lipari**
This plugin is a re-implementation of Edgar A. Leon Borja's mpibind3
script as a spank plugin.

### CODE REVIEW

**Comment by grondo** [comment]
@lipari, I added some minor comments inline. Hopefully they're easy to view that way. I, of course, can't review the function that does the actual binding. Though I'd say it would be easier to understand if the functionality was refactored into a few separate functions instead of all placed into `slurm_spank_task_init`.

Other than these minor comments this looks good.

When you get to the point of trying to build an RPM, libhwloc-devel should be added to the spec file. (or if this is for TOSS3, I guess there will be a separate spec file anyway)

**Comment by lipari** [comment]
@grondo. Just pushed a new commit that addressed your suggestions.  I would have liked to put the whole hwloc code into slurm_spank_user_init() but the SLURM_LOCALID and S_JOB_LOCAL_TASK_COUNT variables were not available until slurm_spank_task_init().
If all looks well, I'll squash the two commits and force push the branch.

**Comment by lipari** [comment]
I have completed my testing.  This rebased pull request is ready for final review and merging.

**Comment by grondo** [comment]
Sorry, this one dropped off my radar. LGTM I think!

**Pull request merged**
